2023-06-07 06:44:49,394 INFO autoreload Watching for file changes with StatReloader
2023-06-07 06:45:03,350 INFO autoreload C:\Users\User\PycharmProjects\DjangoTest3\NewsPaper\news\views.py changed, reloading.
2023-06-07 06:45:03,931 INFO autoreload Watching for file changes with StatReloader
2023-06-07 06:45:04,266 ERROR log Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
2023-06-07 06:45:04,284 ERROR basehttp "GET /news/ HTTP/1.1" 500 145
2023-06-07 06:46:07,959 INFO autoreload C:\Users\User\PycharmProjects\DjangoTest3\NewsPaper\news\views.py changed, reloading.
2023-06-07 06:46:08,579 INFO autoreload Watching for file changes with StatReloader
2023-06-07 06:46:58,011 INFO autoreload C:\Users\User\PycharmProjects\DjangoTest3\NewsPaper\NewsPaper\settings.py changed, reloading.
2023-06-07 06:55:26,785 INFO autoreload Watching for file changes with StatReloader
2023-06-07 06:55:55,346 INFO autoreload C:\Users\User\PycharmProjects\DjangoTest3\NewsPaper\news\views.py changed, reloading.
2023-06-07 06:55:55,969 INFO autoreload Watching for file changes with StatReloader
2023-06-07 06:56:04,764 INFO autoreload C:\Users\User\PycharmProjects\DjangoTest3\NewsPaper\news\views.py changed, reloading.
2023-06-07 06:56:05,404 INFO autoreload Watching for file changes with StatReloader
2023-06-07 06:56:05,574 ERROR log Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
2023-06-07 06:56:05,592 ERROR basehttp "GET /news/ HTTP/1.1" 500 145
2023-06-07 06:57:03,150 INFO autoreload C:\Users\User\PycharmProjects\DjangoTest3\NewsPaper\news\views.py changed, reloading.
2023-06-07 06:57:03,723 INFO autoreload Watching for file changes with StatReloader
2023-06-07 06:57:26,241 INFO autoreload C:\Users\User\PycharmProjects\DjangoTest3\NewsPaper\news\views.py changed, reloading.
2023-06-07 06:57:26,870 INFO autoreload Watching for file changes with StatReloader
2023-06-07 06:57:27,249 ERROR log Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
2023-06-07 06:57:27,270 ERROR basehttp "GET /news/ HTTP/1.1" 500 145
2023-06-07 06:57:43,526 ERROR log Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
2023-06-07 06:57:43,534 ERROR basehttp "GET /news/ HTTP/1.1" 500 145
2023-06-07 06:58:50,233 ERROR log Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
2023-06-07 06:58:50,240 ERROR basehttp "GET /news/ HTTP/1.1" 500 145
2023-06-07 06:59:19,732 INFO autoreload C:\Users\User\PycharmProjects\DjangoTest3\NewsPaper\news\views.py changed, reloading.
2023-06-07 06:59:20,337 INFO autoreload Watching for file changes with StatReloader
2023-06-07 06:59:26,159 ERROR log Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
2023-06-07 06:59:26,174 ERROR basehttp "GET /news/ HTTP/1.1" 500 145
2023-06-07 06:59:45,981 INFO autoreload C:\Users\User\PycharmProjects\DjangoTest3\NewsPaper\news\views.py changed, reloading.
2023-06-07 06:59:46,615 INFO autoreload Watching for file changes with StatReloader
2023-06-07 06:59:46,857 ERROR log Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: news/post_list.html
2023-06-07 06:59:46,877 ERROR basehttp "GET /news/ HTTP/1.1" 500 145
2023-06-07 07:00:18,341 INFO autoreload C:\Users\User\PycharmProjects\DjangoTest3\NewsPaper\news\views.py changed, reloading.
2023-06-07 07:00:18,943 INFO autoreload Watching for file changes with StatReloader
2023-06-07 07:00:19,284 ERROR log Internal Server Error: /news/
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\DjangoTest3\NewsPaper\news\views.py", line 40, in get
    return super().get(request, *args, **kwargs)
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
  File "C:\Users\User\PycharmProjects\DjangoTest3\venv\lib\site-packages\django\views\generic\list.py", line 36, in get_queryset
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: NewsList is missing a QuerySet. Define NewsList.model, NewsList.queryset, or override NewsList.get_queryset().
2023-06-07 07:00:19,300 ERROR basehttp "GET /news/ HTTP/1.1" 500 145
2023-06-07 07:00:53,870 INFO autoreload C:\Users\User\PycharmProjects\DjangoTest3\NewsPaper\news\views.py changed, reloading.
